version: '3.3'
services:
    carbonyl-terminal:
        build: .
        image: carbonyl-terminal
        ports:
            - '127.0.0.1:2222:22'
            - '127.0.0.1:60000-60100:60000-60100/udp'
        dns:
            - 94.140.14.14
            - 94.140.15.15
        container_name: carbonyl
