version: '3.3'
services:
    carbonyl-terminal:
        ports:
            - '2222:22'
            - '60000-60100:60000-60100/udp'
        dns:
            - 94.140.14.14
            - 94.140.15.15
        container_name: carbonyl
        image: carbonyl-terminal
